### DISCUSSION TITLE
How to open generated files in IDEA?

### DISCUSSION THREAD

**Discussion by openallzzz** [j178/leetgo#66] [Q&A] [answered]
`[INFO]  none editor is used, skip opening files`
我用IDEA里的本地终端运行了leetgo，在我准备刷一道题的时候，命令行中提示了这个，我该如何让IDEA识别这个已经生成的文件，并在IDEA中打开？

**Comment by j178** [comment, marked as answer]
Hi

你需要修改 `leetgo.yaml` 文件中 `editor` 部分的配置，因为 IDEA 目前还没有原生支持，你需要用自定义的命令来调用 IDEA。
macOS/Linux 可以在 IDEA 中生成 command line launcher，Windows 系统的话会稍微麻烦一点。

假如你的 IDEA 安装路径是 `C:\Program Files\JetBrains\IntelliJ IDEA` 的话，那么调用命令是 `C:\Program Files\JetBrains\IntelliJ IDEA\bin\idea64.exe`，可以这样配置：
```yaml
editor:
  use: custom
  command: 'C:\Program Files\JetBrains\IntelliJ IDEA\bin\idea64.exe'
```

Ref: https://www.jetbrains.com/help/idea/working-with-the-ide-features-from-command-line.html

**Reply by openallzzz** [reply]
依旧提示`[INFO] none editor is used, skip opening files`

我的配置文件中成功添加了我的IDE安装地址，像你给我发的示例一样。

**Reply by j178** [reply]
应该是配置文件没写对，能发一下完整的配置吗？

**Reply by openallzzz** [reply]
```
language: en
code:
  lang: cpp
leetcode:
  site: https://leetcode.cn
#  credentials:
#    from: browser
editor:
  use: zy
  command: 'D:\devC++5_11\Dev-Cpp\devcpp.exe'
```
