### ISSUE TITLE
[Bug] 同时用chrome和edge的情况下，如何仅识别edge的认证

### ISSUE THREAD

**Issue by liuliangcan** [j178/leetgo#136]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [x]  我已经在 [Issue Tracker](https://github.com/j178/leetgo/issues) 和 [Discussion](https://github.com/j178/leetgo/discussions) 中找过我要提出的问题 I have searched on the [issue tracker](https://github.com/j178/leetgo/issues) and [Discussion](https://github.com/j178/leetgo/discussions) for a related issue. 
- [X]  我已经使用 master 分支版本测试过，问题依旧存在 I have tested using the master branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/j178/leetgo/blob/master/README.md) 并无法自行解决问题 I have read the [documentation](https://github.com/j178/leetgo/blob/master/README.md) and was unable to solve the issue. 

### leetgo config

```shell
Leetgo version info  :
                                             
0.3.0                                           
commit: 2764426ac5844fef41d9131fe33c3d9d23861fc1
built at: 2023-02-25T09:20:06Z                  
goos: windows                                   
goarch: amd64
```
Global config dir    : C:\Users\Administrator\.config\leetgo
Global config file   : C:\Users\Administrator\.config\leetgo\config.yaml
Project root         : F:\play_with_code\play_with_python\tools\leetgo
Working dir          : F:\play_with_code\play_with_python\tools\leetgo
Project config file  : F:\play_with_code\play_with_python\tools\leetgo\leetgo.yaml
Project configuration:

# leetgo project level config, global config is at C:\Users\Administrator\.config\leetgo\config.yaml
# for more details, please refer to https://github.com/j178/leetgo
language: zh
code:
  lang: python3
  filename_template: '{{ .Id | padWithZero 4 }}.{{ .Difficulty }}.{{ .Title }}{{ if .SlugIsMeaningful }}.{{ .Slug }}.{{ .Difficulty }}{{ end }}'
#  python3:
  blocks:
      - name: beforeMarker
        template: |+
          from bisect import *
          from collections import *
          from heapq import *
          from typing import List
          from itertools import *
          from math import inf
          from functools import cache
      - name: beforeCode
        template: |+
          from sortedcontainers import SortedList

leetcode:
  site: https://leetcode.cn
#  credentials:
#    from: browser
#editor:
#  use: none

```
Full configuration   :
```yaml
author: Bob
language: zh
code:
  lang: python3
  filename_template: '{{ .Id | padWithZero 4 }}.{{ .Difficulty }}.{{ .Title }}{{ if .SlugIsMeaningful }}.{{ .Slug }}.{{ .Difficulty }}{{ end }}'
  separate_description_file: false
  blocks:
    - name: beforeMarker
      template: |
        from bisect import *
        from collections import *
        from heapq import *
        from typing import List
        from itertools import *
        from math import inf
        from functools import cache
    - name: beforeCode
      template: |+
        from sortedcontainers import SortedList


  modifiers:
    - name: removeUselessComments
  go:
    out_dir: go
    filename_template: ""
    blocks:
      - name: beforeMarker
  credentials:
    from: browser
    session: ""
    csrftoken: ""
    username: ""
    password: ""
contest:
  out_dir: contest
  filename_template: '{{ .ContestShortSlug }}/{{ .Id }}{{ if .SlugIsMeaningful }}.{{ .Slug }}{{ end }}'
  open_in_browser: true
editor:
  use: none
  command: ""
  args: []
```
```


### Debug log

```shell
PS F:\play_with_code\play_with_python\tools\leetgo> leetgo contest
INFO reading cookies from browser domain=leetcode.cn
? Select a contest:   第 340 场周赛 at 2023/04/09 10:30:00
? Register for 第 340 场周赛 as @leetcode.cn? Yes
INFO registered contest="第 340 场周赛" user=@leetcode.cn
⣽ 第 340 场周赛 begins in 32 minutes 12 seconds, waiting...                     
PS F:\play_with_code\play_with_python\tools\leetgo>
```

### Description

- 我同时使用chrome和edge，（主用edge），chrome曾经登陆过lccn。
- edge是确认已登录状态。
- 现在我注册比赛，出现以下输出，（leetcode.cn不是我的实际账户）：
![image](https://user-images.githubusercontent.com/3946606/230750475-8bbb5dfe-7d0b-4243-9fa3-2b72f981740b.png)
- 然后在edge刷新页面，依然是未注册状态。
- 此时，chrome的登录实际已失效（下图是我用leetgo注册失败后，用chrome打开lccn的截图）
![dc69794ad3ab70824c78f2a465fae93](https://user-images.githubusercontent.com/3946606/230750433-c72e80e3-c90f-4e09-8663-dc18cfdab5df.png)。
- 用chrome打开并确认登录失效后，我再次执行leetgo contest命令，能够正常登录成功了。
---
- 猜测是：chrome里的cookie实际已过期/被踢出，但leetgo未能识别过期现象，使用了它。
