### ISSUE TITLE
[Feature] 请求添加 vscode-insiders 支持

### ISSUE THREAD

**Issue by kardusenor** [j178/leetgo#184]
### Verify steps

- [X]  我已经在 [Issue Tracker](https://github.com/j178/leetgo/issues) 中找过我要提出的请求 I have searched on the [Issue Tracker](https://github.com/j178/leetgo/issues) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/j178/leetgo/blob/master/README.md) 并无法自行解决问题 I have read the [Documentation](https://github.com/j178/leetgo/blob/master/README.md) and was unable to solve the issue. 

### Description

我的电脑只装了 vscode-insiders 没有装 vscode。当我将配置文件中 editor 字段改成 vscode 时无法通过 leetgo edit 命令打开 vscode-insiders编辑代码。

**Comment by j178** [comment]
editor 是支持自定义配置的，比如
```yaml
editor:
  use: custom
  command: /path/to/vscode-insider
  args: ${.Files}
```

表示 用 vscode-insider 打开生成的题目文件。
其中 command 的路径是要根据你的安装路径来的，每个人都不一样。
