### ISSUE TITLE
can not automatically open nvim

### ISSUE THREAD

**Issue by EdwardWong1994** [j178/leetgo#217]
### Verify steps

- [X]  我已经在 [Issue Tracker](https://github.com/j178/leetgo/issues) 和 [Discussion](https://github.com/j178/leetgo/discussions) 中找过我要提出的问题 I have searched on the [Issue Tracker](https://github.com/j178/leetgo/issues) and [Discussion](https://github.com/j178/leetgo/discussions) for a related issue. 

### leetgo debug

Leetgo version info  :
```
1.3.7
commit: 8089d7576f7e8fc9c275acebc854a94feaeaa907
built at: 2023-08-05T08:21:58Z
goos: darwin
goarch: amd64
```
Global config dir    : /Users/wangchenchen/.config/leetgo
Global config file   : /Users/wangchenchen/.config/leetgo/config.yaml
Project root         : /Users/wangchenchen/Desktop/WCC/algorithm/test
Working dir          : /Users/wangchenchen/Desktop/WCC/algorithm/test
Project config file  : /Users/wangchenchen/Desktop/WCC/algorithm/test/leetgo.yaml
Project configuration:
```yaml
# This is the leetgo project level config, global config is at /Users/wangchenchen/.config/leetgo/config.yaml
# For more details, please refer to https://github.com/j178/leetgo
language: zh
code:
  lang: C++
leetcode:
  site: https://leetcode.cn
    #  credentials:
    #    from: browser
  editor:
    use: 'custom'
  command: 'nvim'

```
Full configuration   :
```yaml
author: Edward
language: zh
code:
  lang: C++
  filename_template: '{{ .Id | padWithZero 4 }}{{ if .SlugIsMeaningful }}.{{ .Slug }}{{ end }}'
  separate_description_file: true
  modifiers:
    - name: removeUselessComments
  go:
    out_dir: go
    modifiers:
      - name: removeUselessComments
      - name: changeReceiverName
      - name: addNamedReturn
      - name: addMod
  python3:
    out_dir: python
    executable: python3
  cpp:
    out_dir: cpp
    cxx: g++
    cxxflags: -O2 -std=c++17
  rust:
    out_dir: rust
  java:
    out_dir: java
leetcode:
  site: https://leetcode.cn
  credentials:
    from: browser
    browsers: []
contest:
  out_dir: contest
  filename_template: '{{ .ContestShortSlug }}/{{ .Id }}{{ if .SlugIsMeaningful }}.{{ .Slug }}{{ end }}'
  open_in_browser: true
editor:
  use: none
  command: ""
  args: ""
```

### Description

I have setup the configuration file in `leetgo.yaml` to use `nvim`, also setup in `~/.config/leetgo/config.yaml` to use `vim`
<img width="1440" alt="截屏2023-08-29 下午3 53 58" src="https://github.com/j178/leetgo/assets/96438179/13be4c60-0c79-4924-a8b8-41108827ef2f">

<img width="1440" alt="截屏2023-08-29 下午3 57 41" src="https://github.com/j178/leetgo/assets/96438179/433c89a2-02e3-4a8e-af3a-cf78348a7bdc">

But i do not know why it still can not automatically open `nvim`. The output of `leetgo debug` seems to display that the editor is none. 

I am confused how to configure this properly. Anyone help me to sort out?

**Comment by j178** [comment]
你的原始 issue 里贴的内容有点混乱，我编辑了一下，但还是有点奇怪。

你的 leetgo project 目录是 `/Users/wangchenchen/Desktop/WCC/algorithm/test`, 能在这个目录下执行 `leetgo debug` 并把输出贴过来吗？我主要想确认下 `/Users/wangchenchen/Desktop/WCC/algorithm/test/leetgo.yaml` 这个文件的内容。

**Comment by EdwardWong1994** [comment]
> 你的原始 issue 里贴的内容有点混乱，我编辑了一下，但还是有点奇怪。
> 
> 你的 leetgo project 目录是 `/Users/wangchenchen/Desktop/WCC/algorithm/test` 吗？, 能在这个目录下执行 `leetgo debug` 并把输出贴过来吗？我主要想确认下 `/Users/wangchenchen/Desktop/WCC/algorithm/test/leetgo.yaml` 这个文件的内容。

```
Leetgo version info  :
```
1.3.7
commit: 8089d7576f7e8fc9c275acebc854a94feaeaa907
built at: 2023-08-05T08:21:58Z
goos: darwin
goarch: amd64
```
Global config dir    : /Users/wangchenchen/.config/leetgo
Global config file   : /Users/wangchenchen/.config/leetgo/config.yaml
Project root         : /Users/wangchenchen/Desktop/WCC/algorithm/test
Working dir          : /Users/wangchenchen/Desktop/WCC/algorithm/test
Project config file  : /Users/wangchenchen/Desktop/WCC/algorithm/test/leetgo.yaml
Project configuration:
```yaml
# This is the leetgo project level config, global config is at /Users/wangchenchen/.config/leetgo/config.yaml
# For more details, please refer to https://github.com/j178/leetgo
language: zh
code:
  lang: C++
leetcode:
  site: https://leetcode.cn
    #  credentials:
    #    from: browser
  editor:
    use: 'custom'
    command: 'nvim'
```

这是我在工作目录下的输出，关于`editor`我确实设置了`nvim`,可是我使用`leetgo pick 1`无法自动打开`nvim`，每次都要进入生成的题目文，然后外部执行用vim打开，这样很麻烦
```

**Comment by j178** [comment]
你的缩进错了，editor 是 top-level 的配置项，而不是 leetcode 的子项：
```yaml
language: zh
code:
  lang: C++
leetcode:
  site: https://leetcode.cn
    #  credentials:
    #    from: browser
editor:
  use: 'custom'
  command: 'nvim'
```
