### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by j178** [j178/leetgo#218]
### Verify steps

- [X]  我已经在 [Issue Tracker](https://github.com/j178/leetgo/issues) 和 [Discussion](https://github.com/j178/leetgo/discussions) 中找过我要提出的问题 I have searched on the [Issue Tracker](https://github.com/j178/leetgo/issues) and [Discussion](https://github.com/j178/leetgo/discussions) for a related issue. 

### leetgo debug

```shell
Leetgo version info  :

1.3.7
commit: 8089d7576f7e8fc9c275acebc854a94feaeaa907
built at: 2023-08-05T08:21:58Z
goos: darwin
goarch: amd64
```
Global config dir    : /Users/didi/.config/leetgo
Global config file   : /Users/didi/.config/leetgo/config.yaml
Project root         : /Users/didi/code/leetcode
Working dir          : /Users/didi/code/leetcode
Project config file  : /Users/didi/code/leetcode/leetgo.yaml
Project configuration:

# leetgo project level config, for more details, please refer to https://github.com/j178/leetgo
author: j178
language: en
code:
  lang: go
  separate_description_file: true
leetcode:
  site: https://leetcode.cn
  credentials:
    from: browser
    browsers: ['chrome', 'edge']

```
Full configuration   :
```yaml
author: j178
language: en
code:
  lang: go
  filename_template: '{{ .Id | padWithZero 4 }}{{ if .SlugIsMeaningful }}.{{ .Slug }}{{ end }}'
  separate_description_file: true
  modifiers:
    - name: removeUselessComments
  go:
    out_dir: go
    modifiers:
      - name: removeUselessComments
      - name: changeReceiverName
      - name: addNamedReturn
      - name: addMod
  python3:
    out_dir: python
    executable: python3
  cpp:
    out_dir: cpp
    cxx: g++
    cxxflags: -O2 -std=c++17
  rust:
    out_dir: rust
  java:
    out_dir: java
leetcode:
  site: https://leetcode.cn
  credentials:
    from: browser
    browsers:
      - chrome
      - edge
contest:
  out_dir: contest
  filename_template: '{{ .ContestShortSlug }}/{{ .Id }}{{ if .SlugIsMeaningful }}.{{ .Slug }}{{ end }}'
  open_in_browser: true
editor:
  use: custom
  command: open
  args: -a /Applications/Goland.app {{.CodeFile}}
```
```


### Debug log

_No response_

### Description

test
