### ISSUE TITLE
[Bug] leetgo can't handle `[lints.rust]` in `Cargo.toml` (new feature in rust1.74.0) 

### ISSUE THREAD

**Issue by tchxyc** [j178/leetgo#249]
### leetgo debug

Leetgo version info  :
```
1.3.12
commit: 9cf3325d5110c1ad7e504369ec90c7355ba348ce
built at: 2023-11-19T15:33:03Z
goos: windows
goarch: amd64
```
Project root         : D:\leetcode
Working dir          : D:\leetcode
Project config file  : D:\leetcode\leetgo.yaml
Project configuration:
```yaml
# For more details, please refer to https://github.com/j178/leetgo
language: en
code:
  lang: rust
leetcode:
  site: https://leetcode.com
editor:
  use: custom
  command: "code"
  args: "{{.CodeFile}} {{.DescriptionFile}}"


```
Full configuration   :
```yaml
author: vthe
language: en
code:
  lang: rust
  filename_template: '{{ .Id | padWithZero 4 }}{{ if .SlugIsMeaningful }}.{{ .Slug }}{{ end }}'
  separate_description_file: true
  modifiers:
    - name: removeUselessComments
  go:
    out_dir: go
    modifiers:
      - name: removeUselessComments
      - name: changeReceiverName
      - name: addNamedReturn
      - name: addMod
  python3:
    out_dir: python
    blocks:
      - name: beforeMarker
        template: |2
          from bisect import bisect_left, bisect_right
          from collections import Counter, defaultdict, deque
          from copy import deepcopy
          from functools import cache, cmp_to_key, lru_cache, reduce
          from heapq import heapify, heappop, heappush, heappushpop, heapreplace
          from itertools import accumulate, chain, count, pairwise, zip_longest
          from math import ceil, comb, floor, gcd, inf, isqrt, log2, perm, sqrt
          from operator import xor
          from string import ascii_lowercase
          from typing import List, Optional
      - name: beforeCode
        template: |
          # from sortedcontainers import SortedList
    executable: python.exe
  cpp:
    out_dir: cpp
    cxx: g++
    cxxflags: -O2 -std=c++17
  rust:
    out_dir: rust
    blocks:
      - name: beforeCode
        template: |
          use std::cmp::Reverse;
          use std::collections::*;
          use std::mem::swap;
  java:
    out_dir: java
leetcode:
  site: https://leetcode.com
  credentials:
    from: cookies
    browsers: []
contest:
  out_dir: contest
  filename_template: '{{ .ContestShortSlug }}/{{ .Id }}{{ if .SlugIsMeaningful }}.{{ .Slug }}{{ end }}'
  open_in_browser: true
editor:
  use: custom
  command: code
  args: '{{.CodeFile}} {{.DescriptionFile}}'
```

### Description

```
[lints.rust]
unused_imports = "allow"
```

Each time run `leetgo pick `, `Cargo.toml` will lose the `[lints.rust]` settings.

![Code_ZFLhEVeGvR](https://github.com/j178/leetgo/assets/49787317/52283ebe-d460-4306-82bd-437f9754b13a)

This is a new feature in rust1.74.0, no need to add a header template `#![allow(unused_imports)]` now.

![chrome_9yPwA2fvCe](https://github.com/j178/leetgo/assets/49787317/4f6dea0a-1d52-4ca8-a032-16f34a3b782b)
