### ISSUE TITLE
[Bug] cannot test and submit code

### ISSUE THREAD

**Issue by ChaohaoDu** [j178/leetgo#290]
### leetgo debug

Leetgo version info  :
```
1.4.3
commit: 8953a0bf4f0f4c9d5884674d2d1e2734e4227bc8
built at: 2024-03-20T11:27:56Z
goos: darwin
goarch: amd64
```
Home dir             : /Users/ryan/.config/leetgo
Project root         : /Users/ryan/Desktop/untitled
Working dir          : /Users/ryan/Desktop/untitled
Project config file  : /Users/ryan/Desktop/untitled/leetgo.yaml
Project configuration:
```yaml
# Leetgo configuration file, see more at https://github.com/j178/leetgo

# Your name
author: abc
# Language of the question description: zh or en
language: en
code:
  # Language of code generated for questions: go, cpp, python, java...
  # (will be overridden by command line flag -l/--lang)
  lang: java
  # The default template to generate filename (without extension), e.g. {{.Id}}.{{.Slug}}
  # Available attributes: Id, Slug, Title, Difficulty, Lang, SlugIsMeaningful
  # Available functions: lower, upper, trim, padWithZero, toUnderscore, group
  filename_template: '{{ .Id | padWithZero 4 }}{{ if .SlugIsMeaningful }}.{{ .Slug }}{{ end }}'
  # Generate question description into a separate question.md file
  separate_description_file: true
  # Default modifiers for all languages
  modifiers:
    - name: removeUselessComments
  go:
    out_dir: go
    # Functions that modify the generated code
    modifiers:
      - name: removeUselessComments
      - name: changeReceiverName
      - name: addNamedReturn
      - name: addMod
  python3:
    out_dir: python
    # Python executable that creates the venv
    executable: python3
  cpp:
    out_dir: cpp
    # C++ compiler
    cxx: g++
    # C++ compiler flags (our Leetcode I/O library implementation requires C++17)
    cxxflags: -O2 -std=c++17
  rust:
    out_dir: rust
  java:
    out_dir: java
leetcode:
  # LeetCode site, https://leetcode.com or https://leetcode.cn
  site: https://leetcode.com
  # Credentials to access LeetCode
  credentials:
    # How to provide credentials: browser, cookies, password or none
    from: browser
    # Browsers to get cookies from: chrome, safari, edge or firefox. If empty, all browsers will be tried
    browsers: [safari]
contest:
  # Base dir to put generated contest questions
  out_dir: contest
  # Template to generate filename of the question
  filename_template: '{{ .ContestShortSlug }}/{{ .Id }}{{ if .SlugIsMeaningful }}.{{ .Slug }}{{ end }}'
  # Open the contest page in browser after generating
  open_in_browser: true
# Editor settings to open generated files
editor:
  # Use a predefined editor: vim, vscode, goland
  # Set to 'none' to disable, set to 'custom' to provide your own command
  use: none
  # Custom command to open files
  command: ""
  # Arguments to the command.
  # String contains {{.CodeFile}}, {{.TestFile}}, {{.DescriptionFile}}, {{.TestCasesFile}} will be replaced with corresponding file path.
  # {{.Folder}} will be substituted with the output directory.
  # {{.Files}} will be substituted with the list of all file paths.
  args: ""

```
Full configuration   :
```yaml
author: abc
language: en
code:
  lang: java
  filename_template: '{{ .Id | padWithZero 4 }}{{ if .SlugIsMeaningful }}.{{ .Slug }}{{ end }}'
  separate_description_file: true
  modifiers:
    - name: removeUselessComments
  go:
    out_dir: go
    modifiers:
      - name: removeUselessComments
      - name: changeReceiverName
      - name: addNamedReturn
      - name: addMod
  python3:
    out_dir: python
    executable: python3
  cpp:
    out_dir: cpp
    cxx: g++
    cxxflags: -O2 -std=c++17
  rust:
    out_dir: rust
  java:
    out_dir: java
leetcode:
  site: https://leetcode.com
  credentials:
    from: browser
    browsers:
      - safari
contest:
  out_dir: contest
  filename_template: '{{ .ContestShortSlug }}/{{ .Id }}{{ if .SlugIsMeaningful }}.{{ .Slug }}{{ end }}'
  open_in_browser: true
editor:
  use: none
  command: ""
  args: ""
```

### Debug log

```shell
⣾ Running tests...● retry url=https://leetcode.com/problems/maximum-nesting-depth-of-the-parentheses/interpret_solution/ attempt=0 error="%!v(PANIC=Error method: runtime error: slice bounds out of range [:1024] with length 108)"
⢿ Running tests...● retry url=https://leetcode.com/problems/maximum-nesting-depth-of-the-parentheses/interpret_solution/ attempt=1 error="%!v(PANIC=Error method: runtime error: slice bounds out of range [:1024] with length 108)"
⣷ Running tests...● retry url=https://leetcode.com/problems/maximum-nesting-depth-of-the-parentheses/interpret_solution/ attempt=2 error="%!v(PANIC=Error method: runtime error: slice bounds out of range [:1024] with length 108)"
× failed to run test remotely err="failed to run test: %!v(PANIC=Error method: runtime error: slice bounds out of range [:1024] with length 108)"
```

### Description

cannot submit/test the code
