### ISSUE TITLE
[Bug] Can't submit in leetcode.com

### ISSUE THREAD

**Issue by tchxyc** [j178/leetgo#292]
### leetgo debug

Leetgo version info  :
```
1.4.5
commit: 19a7eb1ba0bc2a376043a1afb5ad4660b046dafe
built at: 2024-04-04T02:09:03Z
goos: windows
goarch: amd64
```
Home dir             : C:\Users\admin\.config\leetgo
Project root         : C:\Users\admin\leetcode
Working dir          : C:\Users\admin\leetcode\rust
Project config file  : C:\Users\admin\leetcode\leetgo.yaml
Project configuration:
```yaml
author: Jones
language: en
code:
  lang: rust
  python3:
    blocks:
    - name: beforeMarker
      template: |

        from bisect import bisect_left, bisect_right
        from collections import Counter, defaultdict, deque
        from copy import deepcopy
        from functools import cache, cmp_to_key, lru_cache, reduce
        from heapq import heapify, heappop, heappush, heappushpop, heapreplace
        from itertools import accumulate, chain, count, pairwise, zip_longest
        from math import ceil, comb, floor, gcd, inf, isqrt, log2, perm, sqrt
        from operator import xor
        from pprint import pprint
        from string import ascii_lowercase
        from typing import List, Optional
  rust:
  blocks:
    - name: beforeCode
      template: |
        use std::cmp::Reverse;
        use std::collections::*;
        use std::mem::swap;
leetcode:
  site: https://leetcode.cn
  credentials:
    from: cookies
contest:
  open_in_browser: false
editor:
  use: custom
  command: "code"
  args: "{{.CodeFile}} {{.DescriptionFile}}"


```
Full configuration   :
```yaml
author: Jones
language: en
code:
  lang: rust
  filename_template: '{{ .Id | padWithZero 4 }}{{ if .SlugIsMeaningful }}.{{ .Slug }}{{ end }}'
  separate_description_file: true
  blocks:
    - name: beforeCode
      template: |
        use std::cmp::Reverse;
        use std::collections::*;
        use std::mem::swap;
  modifiers:
    - name: removeUselessComments
  go:
    out_dir: go
    modifiers:
      - name: removeUselessComments
      - name: changeReceiverName
      - name: addNamedReturn
      - name: addMod
  python3:
    out_dir: python
    blocks:
      - name: beforeMarker
        template: |2
          from bisect import bisect_left, bisect_right
          from collections import Counter, defaultdict, deque
          from copy import deepcopy
          from functools import cache, cmp_to_key, lru_cache, reduce
          from heapq import heapify, heappop, heappush, heappushpop, heapreplace
          from itertools import accumulate, chain, count, pairwise, zip_longest
          from math import ceil, comb, floor, gcd, inf, isqrt, log2, perm, sqrt
          from operator import xor
          from pprint import pprint
          from string import ascii_lowercase
          from typing import List, Optional
    executable: python.exe
  cpp:
    out_dir: cpp
    cxx: g++
    cxxflags: -O2 -std=c++17
  rust:
    out_dir: rust
  java:
    out_dir: java
leetcode:
  site: https://leetcode.cn
  credentials:
    from: cookies
    browsers: []
contest:
  out_dir: contest
  filename_template: '{{ .ContestShortSlug }}/{{ .Id }}{{ if .SlugIsMeaningful }}.{{ .Slug }}{{ end }}'
  open_in_browser: false
editor:
  use: custom
  command: code
  args: '{{.CodeFile}} {{.DescriptionFile}}'
```

### Description

```
lc test last -Ls --site us
● running test locally question=make-the-string-great
● building file=src/1544.make-the-string-great/solution.rs
● Case 1:    Passed
● Case 2:    Passed
● Case 3:    Passed
● submitting solution user=@leetcode.com
⣻ Submitting solution...● retry url=https://leetcode.com/problems/make-the-string-great/submit/ attempt=0 error="[403 Forbidden] <empty>"
⣾ Submitting solution...● retry url=https://leetcode.com/problems/make-the-string-great/submit/ attempt=1 error="[403 Forbidden] <empty>"
⣾ Submitting solution...● retry url=https://leetcode.com/problems/make-the-string-great/submit/ attempt=2 error="[403 Forbidden] <empty>"
× failed to submit solution err="failed to submit solution: [403 Forbidden] <empty>"
```

Something strange here, `● submitting solution user=@leetcode.com`, seems like it doesn't recognize my username
I tried changing my cookies but the problem persists.
