### ISSUE TITLE
[Bug] Can't parse past contests correctly.

### ISSUE THREAD

**Issue by rgbygv** [j178/leetgo#374]
### leetgo debug

root@xxx ~/leetcode (master) [2]# lc debug
Leetgo version info  :
```
dev
commit: HEAD
built at: unknown
goos: linux
goarch: amd64
```
Home dir             : /root/.config/leetgo
Project root         : /root/leetcode
Working dir          : /root/leetcode
Project config file  : /root/leetcode/leetgo.yaml
Project configuration:
```yaml
author: none
language: en
code:
  lang: python3
  cpp:
    cxx: clang++
    cxxflags: -O2 -std=c++23
  python3:
    blocks:
    - name: beforeMarker
      template: |

        from bisect import bisect_left, bisect_right
        from collections import Counter, defaultdict, deque
        from functools import cache, cmp_to_key, lru_cache, reduce
        from heapq import heapify, heappop, heappush, heappushpop, heapreplace
        from itertools import accumulate, chain, count, pairwise, zip_longest
        from math import ceil, comb, floor, gcd, inf, isqrt, lcm, log2, perm, sqrt
        from operator import xor
        from pprint import pprint
        from string import ascii_lowercase
        from typing import List, Optional
  go:
    modifiers:
      - name: removeUselessComments
      - name: changeReceiverName
      # - name: addNamedReturn
      # - name: addMod       
  # rust:
  # blocks:
  #   - name: beforeCode
  #     template: |
  #       use std::cmp::Reverse;
  #       use std::collections::*;
  #       use std::mem::swap;
leetcode:
  site: https://leetcode.com
  credentials:
    from: cookies
contest:
  open_in_browser: false
editor:
  use: custom
  command: "code"
  args: "{{.CodeFile}} {{.DescriptionFile}}"


```
Full configuration   :
```yaml
author: none
language: en
code:
  lang: python3
  filename_template: '{{ .Id | padWithZero 4 }}{{ if .SlugIsMeaningful }}.{{ .Slug }}{{ end }}'
  separate_description_file: true
  modifiers:
    - name: removeUselessComments
  go:
    out_dir: go
    modifiers:
      - name: removeUselessComments
      - name: changeReceiverName
  python3:
    out_dir: python
    blocks:
      - name: beforeMarker
        template: |2
          from bisect import bisect_left, bisect_right
          from collections import Counter, defaultdict, deque
          from functools import cache, cmp_to_key, lru_cache, reduce
          from heapq import heapify, heappop, heappush, heappushpop, heapreplace
          from itertools import accumulate, chain, count, pairwise, zip_longest
          from math import ceil, comb, floor, gcd, inf, isqrt, lcm, log2, perm, sqrt
          from operator import xor
          from pprint import pprint
          from string import ascii_lowercase
          from typing import List, Optional
    executable: python3
  cpp:
    out_dir: cpp
    cxx: clang++
    cxxflags: -O2 -std=c++23
  rust:
    out_dir: rust
  java:
    out_dir: java
leetcode:
  site: https://leetcode.com
  credentials:
    from:
      - cookies
    browsers: []
contest:
  out_dir: contest
  filename_template: '{{ .ContestShortSlug }}/{{ .Id }}{{ if .SlugIsMeaningful }}.{{ .Slug }}{{ end }}'
  open_in_browser: false
editor:
  use: custom
  command: code
  args: '{{.CodeFile}} {{.DescriptionFile}}'
```

### Debug log

```shell

```

### Description

```fish
root@xxx ~/leetcode (master) [2]# lc contest 
? Select a contest:  [Use arrows to move, type to filter]
>   Biweekly Contest 159 at 2025/06/21 22:30:00
    Weekly Contest 455 at 2025/06/22 10:30:00
× interrupt
root@xxx ~/leetcode (master) [1]# lc contest w454
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/PuerkitoBio/goquery.(*Selection).Get(...)
        /root/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.10.2/array.go:77
github.com/j178/leetgo/leetcode.parseContestHtml({0xc0007da000, 0x29256, 0x2a000}, {0xc0007945b3, 0x1e}, {0x11229e2, 0x14})
        /root/leetgo/leetcode/client.go:703 +0x12b2
github.com/j178/leetgo/leetcode.(*usClient).GetContestQuestionData(0xc0004ca440, {0xc00017d2c0?, 0x41b2a5?}, {0xc0007945b3, 0x1e})
        /root/leetgo/leetcode/client_us.go:213 +0x3f2
github.com/j178/leetgo/leetcode.(*QuestionData).Fulfill(0xc0005ea288)
        /root/leetgo/leetcode/question.go:361 +0x51
github.com/j178/leetgo/lang.generate(0xc0005ea288)
        /root/leetgo/lang/gen.go:49 +0x71
github.com/j178/leetgo/lang.GenerateContest(0xc000262000)
        /root/leetgo/lang/gen.go:138 +0xdf
github.com/j178/leetgo/cmd.init.func3(0x1dfcac0, {0xc0005972b0, 0x1, 0x10f8cd6?})
        /root/leetgo/cmd/contest.go:210 +0x6e5
github.com/spf13/cobra.(*Command).execute(0x1dfcac0, {0xc000597270, 0x1, 0x1})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1015 +0xaaa
github.com/spf13/cobra.(*Command).ExecuteC(0x1dfee80)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1148 +0x46f
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1071
github.com/j178/leetgo/cmd.Execute()
        /root/leetgo/cmd/root.go:52 +0x1e
main.main()
        /root/leetgo/main.go:6 +0xf
root@xxx~/leetcode (master) [2]# 
```

It seems that LeetCode has changed the UI of contest, so the HTML parser can't correctly find the questions.
