### ISSUE TITLE
File template support

### ISSUE THREAD

**Issue by Paren7** [j178/leetgo#64]
When we use IDEs for cpp code writing, the code of mainstream IDEs automatically prompts from the introduction of header files, such as clion, so it is better to introduce automatically
```
#include<bits/stdc++.h>
using namespace std;
```
Of course it would be better to create the file as a template, because many c++ users use some macro definitions to simplify the code

**Comment by j178** [comment]
Thanks.

File template is a good idea, I was thinking something that too, will try to implement it.

**Comment by j178** [comment]
@Paren7 Hi, I just released `v0.1.5-beta` with file template support, would you try it?

I introduced `blocks` and `modifiers` for every language, user can use `blocks` to customize some blocks of the generated code, and use `modfiers` to change the code content. For your case, you can configure like this:
```yaml
code:
  cpp:
    blocks:
    - name: beforeCode
      template: |
        #include<bits/stdc++.h>
        using namespace std;
```
