### ISSUE TITLE
feedbak

### ISSUE THREAD

**Issue by Zhangyu-0427** [j178/leetgo#65]
`[INFO]  none editor is used, skip opening files`
我用IDEA里的本地终端运行了leetgo，在我准备刷一道题的时候，命令行中提示了这个，我该如何让IDEA识别这个已经生成的文件，并在IDEA中打开？

**Comment by j178** [comment]
Hi

你需要修改 `leetgo.yaml` 文件中 `editor` 部分的配置，因为 IDEA 目前还没有原生支持，你需要用自定义的命令来调用 IDEA。
macOS/Linux 可以在 IDEA 中生成 command line launcher，Windows 系统的话会稍微麻烦一点。

假如你的 IDEA 安装路径是 `C:\Program Files\JetBrains\IntelliJ IDEA` 的话，那么调用命令是 `C:\Program Files\JetBrains\IntelliJ IDEA\bin\idea64.exe`，可以这样配置：
```yaml
editor:
  use: custom
  command: 'C:\Program Files\JetBrains\IntelliJ IDEA\bin\idea64.exe'
```
